### ISSUE TITLE
Reading Traditional Intan File Format

### ISSUE THREAD

**Issue by emmalala123** [katzlabbrandeis/blech_clust#238]
"Saves all waveforms in one file, along with records of sampling rate, amplifier bandwidth, chennel names, etc. A new file is created every N minutes."

We currently don't have reader for this and it is the default file format option on the Intan software.

File list: 

eb24_behandephys_11_12_24_241112_114659.rhd
eb24_behandephys_11_12_24_241112_114759.rhd
eb24_behandephys_11_12_24_241112_114859.rhd
eb24_behandephys_11_12_24_241112_114959.rhd
eb24_behandephys_11_12_24_241112_115059.rhd
eb24_behandephys_11_12_24_241112_115159.rhd
eb24_behandephys_11_12_24_241112_115259.rhd
eb24_behandephys_11_12_24_241112_115359.rhd
eb24_behandephys_11_12_24_241112_115459.rhd
eb24_behandephys_11_12_24_241112_115559.rhd
eb24_behandephys_11_12_24_241112_115659.rhd
eb24_behandephys_11_12_24_241112_115759.rhd
eb24_behandephys_11_12_24_241112_115859.rhd
eb24_behandephys_11_12_24_241112_115959.rhd
eb24_behandephys_11_12_24_241112_120059.rhd
eb24_behandephys_11_12_24_241112_120159.rhd
eb24_behandephys_11_12_24_241112_120259.rhd
eb24_behandephys_11_12_24_241112_120359.rhd
eb24_behandephys_11_12_24_241112_120459.rhd
eb24_behandephys_11_12_24_241112_120559.rhd
eb24_behandephys_11_12_24_241112_120659.rhd
eb24_behandephys_11_12_24_241112_120759.rhd
eb24_behandephys_11_12_24_241112_120859.rhd
eb24_behandephys_11_12_24_241112_120959.rhd
eb24_behandephys_11_12_24_241112_121059.rhd
eb24_behandephys_11_12_24_241112_121159.rhd
eb24_behandephys_11_12_24_241112_121259.rhd
eb24_behandephys_11_12_24_241112_121359.rhd
eb24_behandephys_11_12_24_241112_121459.rhd
eb24_behandephys_11_12_24_241112_121559.rhd
eb24_behandephys_11_12_24_241112_121659.rhd
eb24_behandephys_11_12_24_241112_121759.rhd
eb24_behandephys_11_12_24_241112_121859.rhd
eb24_behandephys_11_12_24_241112_121959.rhd
eb24_behandephys_11_12_24_241112_122059.rhd
eb24_behandephys_11_12_24_241112_122159.rhd
eb24_behandephys_11_12_24_241112_122259.rhd
eb24_behandephys_11_12_24_241112_122359.rhd
eb24_behandephys_11_12_24_241112_122459.rhd
eb24_behandephys_11_12_24_241112_122559.rhd
eb24_behandephys_11_12_24_241112_122659.rhd
eb24_behandephys_11_12_24_241112_122759.rhd
eb24_behandephys_11_12_24_241112_122859.rhd
eb24_behandephys_11_12_24_241112_122959.rhd
eb24_behandephys_11_12_24_241112_123059.rhd
eb24_behandephys_11_12_24_241112_123159.rhd
eb24_behandephys_11_12_24_241112_123259.rhd
eb24_behandephys_11_12_24_241112_123359.rhd
eb24_behandephys_11_12_24_241112_123459.rhd
eb24_behandephys_11_12_24_241112_123559.rhd
eb24_behandephys_11_12_24_241112_123659.rhd
eb24_behandephys_11_12_24_241112_123759.rhd
eb24_behandephys_11_12_24_241112_123859.rhd
eb24_behandephys_11_12_24_241112_123959.rhd
eb24_behandephys_11_12_24_241112_124059.rhd
eb24_behandephys_11_12_24_241112_124159.rhd
eb24_behandephys_11_12_24_241112_124259.rhd
eb24_behandephys_11_12_24_241112_124359.rhd
eb24_behandephys_11_12_24_241112_124459.rhd
eb24_behandephys_11_12_24_241112_124559.rhd
eb24_behandephys_11_12_24_241112_124659.rhd
settings.xml

**Comment by abuzarmahmood** [comment]
This was present around commit 91e340ffd15b10fa5cb93e1947ffb6107410bee0
Will have to update `read_file.py` to allow reading this format

**Comment by abuzarmahmood** [comment]
Code to read traditional format has been merged, please reopen issue if any errors occur
