### ISSUE TITLE
Voltage cutoff detection params

### ISSUE THREAD

**Issue by emmalala123** [katzlabbrandeis/blech_clust#239]
Hello! What are the units for this cutoff param? The number is 10,000, currently.

Thanks!

**Comment by emmalala123** [comment]
Also mark on cut_off plot where cutoff voltage threshold is...for visual reference

**Comment by abuzarmahmood** [comment]
The parameter is in millivolts...PR #255 will add threshold markers to the mean voltage plot.
I've upgraded issue #27 to move to a params file that allows comments
