### ISSUE TITLE
Need the sum to be more than 1 .rhd file detected for traditional file format. Thanks!!

### ISSUE THREAD

**Issue by emmalala123** [katzlabbrandeis/blech_clust#258]
# Find all ports used
    file_list = os.listdir(dir_path)
    if 'auxiliary.dat' in file_list:
        file_type = ['one file per signal type']
    elif sum(['rhd' in x for x in file_list]) > 1:
        file_type = ['traditional']
    else:
        file_type = ['one file per channel']
        
    print(f'Detected file type : {file_type}')

**Comment by abuzarmahmood** [comment]
Fixed in latest version of master 
https://github.com/katzlabbrandeis/blech_clust/blob/6ceb470ad57446712bc49bf874a743428954b9da/blech_clust.py#L249
